### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [lily0023/okogoto#83]
@lily0023 
お疲れ様です。
下記の観点でMVPレビュー行いました。

```
1. 就活において十分な技術力を示せる機能を実装しているか
2. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
```

### 1について
- Fat Controllerになっている箇所が散見されたので、rubocopを通して指摘箇所があった場合は、モデル等にメソッドとして切り出しましょう。
- テストコードがほとんど書いていない状態ですので、就活時には主要な機能の部分にテストコードが用意されている状態にしましょう。（100%カバーしている必要はありません。30〜50%くらいの温度感で大丈夫です）

### 2について
実際に触ってみて気になった部分になります。
- 全体的に文字が見にくく感じました。文字の色をいくつか試してみて読みやすいものを選択すると良いかと思います。
- ログイン成功後、投稿一覧ではなくLPページに遷移するのが、やや不自然に感じました。
- オコゴト画像を作成した後に、editページに遷移して「コメント」「タグ」「オオゴト画像を投稿する」が表示されたためか、投稿が成功したのかがハッキリと分からなかったです。
- ログイン時に左上のロゴを押した際に、LPページに遷移してしまうのが気になりました。（一覧にもどるかと思ってました）
- オコゴトがない状態でも投稿できてしまったので、バリデーションエラーを起こしてエラーメッセージが出るようにすると良いかと感じました。

### 所感
「2について」を早急に対応いただいて、それが終わり次第、就活の準備等を進めていただいて大丈夫かと思いました。就活と並行して「1について」や追加機能の実装を進めましょう。

**Comment by lily0023** [comment]
@Tsuchiya2 
レビューありがとうございます。
#### 1について
Fat Controllerとテストコード、承知いたしました。２についての対応終わり次第取り組みます！

#### 2について
- 色についてTwitterでもご意見いただいたので、文字の大きさや配色も読みやすさという観点も含めて再度検討してみます。
- 確かにログインしたユーザーに紹介するのはおかしいですね。。。ご指摘ありがとうございます、ロゴの遷移先も同様にすぐ変更します！

> オコゴト画像を作成した後に、editページに遷移して「コメント」「タグ」「オオゴト画像を投稿する」が表示されたためか、投稿が成功したのかがハッキリと分からなかったです。

> オコゴトがない状態でも投稿できてしまったので、バリデーションエラーを起こしてエラーメッセージが出るようにすると良いかと感じました。

この２つの件について実は、ここが実装中にもかなり悩んだところで少しお伺いしたいです。
[![Image from Gyazo](https://i.gyazo.com/d2b16d1e2ced5caabcc329c02d3c314d.png)](https://gyazo.com/d2b16d1e2ced5caabcc329c02d3c314d)
オコゴト画像に関しては実は作成した画像がpostsテーブルにkogoto_imageとして保存されるだけで、オコゴトの内容となんの背景を選択したかについてはDBに登録していない状態です。
それが原因でオコゴトの入力フォームに70文字の制限をつけるだけの曖昧な対応になってしまっています。

完全に調査不足で、初めはokogoto_images controllerでオコゴト画像を作成して、そのデータをposts controllerのnewアクションに渡すことができないかなと試行錯誤していたのですが、なかなかうまくいかなくて、やむを得ずオコゴト画像を作成しただけの段階でPost.newして、そこからposts controllerのeditアクションに移動して後からコメントとタグを追加する形にして誤魔化した感じになってしまいました。。。

ご指摘いただいたように入力するオコゴト自体にvalidationをつける、画像を作成した後newページに遷移させるためには
1. okogoto_imagesテーブルを追加して、そこにオコゴトと選択した背景を保存する
2. post controllerのnewアクションでokogoto_imagesテーブルに保存した情報を使って画像を生成して、投稿作成画面に表示させ、コメントとタグを入力する
という流れなら、今保存されている画像を削除せずに機能追加できますでしょうか・・・？

ダラダラとわかりにくくてすみません・・・。ぜひご意見お伺いしたいです、よろしくお願いします。
レビュー内容についてはまずはすぐ直せるところから取り掛からせていただきます、ありがとうございます！

**Comment by Tsuchiya2** [comment]
> オコゴト画像に関しては実は作成した画像がpostsテーブルにkogoto_imageとして保存されるだけで、オコゴトの内容となんの背景を選択したかについてはDBに登録していない状態です。
それが原因でオコゴトの入力フォームに70文字の制限をつけるだけの曖昧な対応になってしまっています。

状況が良くわらず推測になってしまいますが...以下のコードは画像を生成する機能ということですかね？

```ruby
class OkogotoImagesController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    okogoto = kogoto_params[:okogoto]
    okogoto_image = case params[:image]
                    when 'kakugen'
                      KakugenImage.build(okogoto)
                    when 'kogoto'
                      KogotoImage.build(okogoto)
                    when 'friends'
                      FriendsImage.build(okogoto)
                    end
    @post = current_user.posts.new(kogoto_image: okogoto_image)
    if @post.save
      redirect_to edit_post_path(@post), flash: { success: t('.success') }
    else
      flash.now[:error] = t('.fail')
      render :new, status: :unprocessable_entity
    end
  end

  private

  def kogoto_params
    params.permit(:okogoto, :image)
  end
end
```

`if @post.save ...`のelse部分はどういった際に処理されるのかが気になりましたが...。

`okogoto = kogoto_params[:okogoto]`の部分がblankだったら、else部分に書かれているような処理が実行されるようにしたら良いかもしれません。

```ruby
 okogoto = kogoto_params[:okogoto]

ir okogoto.blank?
  flash.now[:error] = `オコゴトが未入力です`
  render :new, status: :unprocessable_entity
end

 okogoto_image = case params[:image]
```

↑思いつきのコードなのでご自身で試してみて、成功したらFat Controllerを解消できるようにしてみてください。
